### PR TITLE
Various improvements, using Shiki

### PR DESCRIPTION
**Pull request by mercmobily**
Added improvements from seb insua

### CODE REVIEW

**Comment by mercmobily** [comment]
this is merged

**Comment by mercmobily** [comment]
I am still checking that everything works. Since you made the changes, I updated a lot of libraries, I am checking that I merged it right

**Comment by sebinsua** [comment]
@mercmobily You'll need to change the package name back from `@duplotech/docco-next` to `docco-next`. I changed it so I could publish a fork.

**Edit**: Oh, I see you've fixed the name in `master`.

**Comment by mercmobily** [comment]
Yep I did. I realised the mistake once I merged this...

**Comment by mercmobily** [comment]
I gave you publishing rights on NPM for the package, as well as writing access to this repository. Please drop me an email so that we can talk in private if you like!

**Comment by mercmobily** [comment]
tonymobily@gmail.com

**Comment by mercmobily** [comment]
@sebinsua Are you happy to maintain docco-next together? It's not much work, since it's essentially finished. But it would be good to know that you are onboard.

**Comment by mercmobily** [comment]
@sebinsua ? :D

**Comment by sebinsua** [comment]
@mercmobily Yes, I'd be happy to help maintain this with you. Not expecting to submit a lot more code myself, but can review any PRs that come in. (Sorry for the tardy response - I just had a baby so have difficulty keeping up with everything.)

**Comment by mercmobily** [comment]
You just had a baby!!!
Super congratulations. Is it your first one?
I have two -- well, not babies anymore, they are 7 and 9 -- but I will
leave you in peace. I just wanted to make sure you were onboard with this :D

It's very low maintenance... I mean, it works. There are a few bits and
pieces I want to improve, and would love to have another set of eyes to
check things before I release.

But really, no stress, no rush, no worries, thanks for your help, and
congrats on your new baby!

**Pull request merged**
